package victronDevice

var RegisterListBmvProduct = VictronRegisters{
	CreateNumberRegisterStruct(
		"Product",
		"ProductId",
		"Product id",
		0x0100,
		true,
		false,
		1,
		"",
		200,
	),
	CreateNumberRegisterStruct(
		"Product",
		"ProductRevision",
		"Product revision",
		0x0101,
		true,
		false,
		1,
		"",
		201,
	),
	CreateTextRegisterStruct(
		"Product",
		"SerialNumber",
		"Serial number",
		0x010A,
		true,
		202,
	),
	CreateTextRegisterStruct(
		"Product",
		"ModelName",
		"Model name",
		0x010B,
		true,
		203,
	),
	CreateTextRegisterStruct(
		"Product",
		"Description",
		"Description",
		0x010C,
		true,
		204,
	),
	CreateNumberRegisterStruct(
		"Product",
		"Uptime",
		"Device uptime",
		0x0120,
		false,
		false,
		1,
		"s",
		205,
	),
	// skipped Bluetooth capabilities
}

var RegisterListBmvMonitor = VictronRegisters{
	CreateNumberRegisterStruct(
		"Essential",
		"Power",
		"Power",
		0xED8E,
		false,
		true,
		1,
		"W",
		0,
	), CreateNumberRegisterStruct(
		"Essential",
		"CurrentHighRes",
		"Current",
		0xED8C,
		false,
		true,
		1000,
		"A",
		1,
	),
	CreateNumberRegisterStruct(
		"Essential",
		"MainVoltage",
		"Main voltage",
		0xED8D,
		false,
		true,
		100,
		"V",
		2,
	),
	CreateNumberRegisterStruct(
		"Monitor",
		"AuxVoltage",
		"Aux (starter) voltage",
		0xED7D,
		false,
		false,
		100,
		"V",
		100,
	),
	CreateNumberRegisterStruct(
		"Monitor",
		"Consumed",
		"Consumed",
		0xEEFF,
		false,
		true,
		10,
		"Ah",
		101,
	), CreateNumberRegisterStruct(
		"Essential",
		"SOC",
		"State of charge",
		0x0FFF,
		false,
		false,
		100,
		"%",
		3,
	), CreateNumberRegisterStruct(
		"Monitor",
		"TTG",
		"Time to go",
		0x0FFE,
		false,
		false,
		1,
		"min",
		102,
	), CreateNumberRegisterStruct(
		"Essential",
		"BatteryTemperature",
		"Battery Temperature",
		0xEDEC,
		false,
		false,
		100,
		"K",
		4,
	), CreateNumberRegisterStruct(
		"Monitor",
		"MidPointVoltage",
		"Mid-point voltage",
		0x0382,
		false,
		false,
		100,
		"V",
		104,
	), CreateNumberRegisterStruct(
		"Monitor",
		"MidPointVoltageDeviation",
		"Mid-point voltage deviation",
		0x0383,
		false,
		true,
		10,
		"%",
		105,
	), CreateEnumRegisterStruct(
		"Monitor",
		"SynchronizationState",
		"Synchronization state",
		0xEEB6,
		false,
		map[int]string{
			0: "false",
			1: "true",
		},
		106,
	),
}

var RegisterListBmvHistoric = VictronRegisters{
	CreateNumberRegisterStruct(
		"Historic",
		"DepthOfTheDeepestDischarge",
		"Depth of the deepest discharge",
		0x0300,
		false,
		true,
		10,
		"Ah",
		300,
	), CreateNumberRegisterStruct(
		"Historic",
		"DepthOfTheLastDischarge",
		"Depth of the last discharge",
		0x0301,
		false,
		true,
		10,
		"Ah",
		301,
	), CreateNumberRegisterStruct(
		"Historic",
		"DepthOfTheAverageDischarge",
		"Depth of the average discharge",
		0x0302,
		false,
		true,
		10,
		"Ah",
		302,
	), CreateNumberRegisterStruct(
		"Historic",
		"NumberOfCycles",
		"Number of cycles",
		0x0303,
		false,
		false,
		1,
		"",
		303,
	), CreateNumberRegisterStruct(
		"Historic",
		"NumberOfFullDischarges",
		"Number of full discharges",
		0x0304,
		false,
		false,
		1,
		"",
		304,
	), CreateNumberRegisterStruct(
		"Historic",
		"CumulativeAmpHours",
		"Cumulative amp hours",
		0x0305,
		false,
		true,
		10,
		"Ah",
		305,
	), CreateNumberRegisterStruct(
		"Historic",
		"MainVoltageMinimum",
		"Minimum voltage",
		0x0306,
		false,
		false,
		100,
		"V",
		306,
	), CreateNumberRegisterStruct(
		"Historic",
		"MainVoltageMaximum",
		"Maximum voltage",
		0x0307,
		false,
		false,
		100,
		"V",
		307,
	), CreateNumberRegisterStruct(
		"Historic",
		"TimeSinceFullCharge",
		"Time since full charge",
		0x0308,
		false,
		false,
		1,
		"s",
		308,
	), CreateNumberRegisterStruct(
		"Historic",
		"NumberOfAutomaticSynchronizations",
		"Number of automatic synchronizations",
		0x0309,
		false,
		false,
		1,
		"",
		309,
	), CreateNumberRegisterStruct(
		"Historic",
		"NumberOfLowMainVoltageAlarms",
		"Number of low voltage alarms",
		0x030A,
		false,
		false,
		1,
		"",
		310,
	), CreateNumberRegisterStruct(
		"Historic",
		"NumberOfHighMainVoltageAlarms",
		"Number of high voltage alarms",
		0x030B,
		false,
		false,
		1,
		"",
		311,
	), CreateNumberRegisterStruct(
		"Historic",
		"AuxVoltageMinimum",
		"Minimum starter voltage",
		0x030E,
		false,
		true,
		100,
		"V",
		312,
	), CreateNumberRegisterStruct(
		"Historic",
		"AuxVoltageMaximum",
		"Maximum starter voltage",
		0x030F,
		false,
		true,
		100,
		"V",
		313,
	), CreateNumberRegisterStruct(
		"Historic",
		"AmountOfDischargedEnergy",
		"Amount of discharged energy",
		0x0310,
		false,
		false,
		100,
		"kWh",
		314,
	), CreateNumberRegisterStruct(
		"Historic",
		"AmountOfChargedEnergy",
		"Amount of charged energy",
		0x0311,
		false,
		false,
		100,
		"kWh",
		315,
	),
}

var RegisterListBmv = MergeRegisters(
	RegisterListBmvMonitor,
	RegisterListBmvProduct,
	RegisterListBmvHistoric,
)

var RegisterListBmv712 = FilterRegistersByName(
	RegisterListBmv,
	"ProductRevision",
	"Description",
)

var RegisterListBmv702 = FilterRegistersByName(
	RegisterListBmv,
	"ProductRevision",
	"Description",
)

var RegisterListBmv700 = FilterRegistersByName(
	RegisterListBmv,
	"AuxVoltage",
	"BatteryTemperature",
	"MidPointVoltage",
	"MidPointVoltageDeviation",
	"AuxVoltageMinimum",
	"AuxVoltageMaximum",
)
