package vedevices

var RegisterListBmv700Essential = Registers{
	Register{
		Name:          "MainVoltage",
		Description:   "",
		Address:       0xED8D,
		Factor:        0.01,
		Unit:          "V",
		Signed:        false,
		RoundDecimals: 2,
	},
	Register{
		Name:          "Current",
		Description:   "",
		Address:       0xED8F,
		Factor:        0.1,
		Unit:          "A",
		Signed:        true,
		RoundDecimals: 1,
	},
	Register{
		Name:          "Power",
		Description:   "",
		Address:       0xED8E,
		Factor:        1,
		Unit:          "W",
		Signed:        true,
		RoundDecimals: 0,
	},
}

var RegisterListBmv700 = mergeRegisters(
	RegisterListBmv700Essential,
	Registers{
		Register{
			Name:          "Consumed",
			Description:   "",
			Address:       0xEEFF,
			Factor:        0.1,
			Unit:          "Ah",
			Signed:        true,
			RoundDecimals: 1,
		},
		Register{
			Name:          "StateOfCharge",
			Description:   "",
			Address:       0x0FFF,
			Factor:        0.01,
			Unit:          "%",
			Signed:        false,
			RoundDecimals: 0,
		},
		Register{
			Name:          "TimeToGo",
			Description:   "",
			Address:       0x0FFE,
			Factor:        1,
			Unit:          "min",
			Signed:        false,
			RoundDecimals: 0,
		},
		Register{
			Name:          "Temperature",
			Description:   "",
			Address:       0xEDEC,
			Factor:        0.01,
			Unit:          "K",
			Signed:        false,
			RoundDecimals: 1,
		},
		Register{
			Name:          "DepthOfTheDeepestDischarge",
			Description:   "",
			Address:       0x0300,
			Factor:        0.1,
			Unit:          "Ah",
			Signed:        true,
			RoundDecimals: 0,
		},
		Register{
			Name:          "DepthOfTheLastDischarge",
			Description:   "",
			Address:       0x0301,
			Factor:        0.1,
			Unit:          "Ah",
			Signed:        true,
			RoundDecimals: 0,
		},
		Register{
			Name:          "DepthOfTheAverageDischarge",
			Description:   "",
			Address:       0x0302,
			Factor:        0.1,
			Unit:          "Ah",
			Signed:        true,
			RoundDecimals: 0,
		},
		Register{
			Name:          "NumberOfCycles",
			Description:   "",
			Address:       0x0303,
			Factor:        1,
			Unit:          "",
			Signed:        false,
			RoundDecimals: 0,
		},
		Register{
			Name:          "NumberOfFullDischarges",
			Description:   "",
			Address:       0x0304,
			Factor:        1,
			Unit:          "",
			Signed:        false,
			RoundDecimals: 0,
		},
		"CumulativeAmpHours": Register{
			Description:   "",
			Address:       0x0305,
			Factor:        0.1,
			Unit:          "Ah",
			Signed:        true,
			RoundDecimals: 0,
		},
		"MainVoltageMinimum": Register{
			Description:   "",
			Address:       0x0306,
			Factor:        0.01,
			Unit:          "V",
			Signed:        false,
			RoundDecimals: 2,
		},
		"MainVoltageMaximum": Register{
			Description:   "",
			Address:       0x0307,
			Factor:        0.01,
			Unit:          "V",
			Signed:        false,
			RoundDecimals: 2,
		},
		"HoursSinceFullCharge": Register{
			Description:   "",
			Address:       0x0308,
			Factor:        float64(24) / float64(86400),
			Unit:          "h",
			Signed:        false,
			RoundDecimals: 1,
		},
		"NumberOfAutomaticSynchronizations": Register{
			Description:   "",
			Address:       0x0309,
			Factor:        1,
			Unit:          "",
			Signed:        false,
			RoundDecimals: 0,
		},
		"NumberOfLowMainVoltageAlarms": Register{
			Description:   "",
			Address:       0x030A,
			Factor:        1,
			Unit:          "",
			Signed:        false,
			RoundDecimals: 0,
		},
		"NumberOfHighMainVoltageAlarms": Register{
			Description:   "",
			Address:       0x030B,
			Factor:        1,
			Unit:          "",
			Signed:        false,
			RoundDecimals: 0,
		},
		"AmountOfDischargedEnergy": Register{
			Description:   "",
			Address:       0x0310,
			Factor:        0.01,
			Unit:          "kWh",
			Signed:        false,
			RoundDecimals: 1,
		},
		"AmountOfChargedEnergy": Register{
			Description:   "",
			Address:       0x0311,
			Factor:        0.01,
			Unit:          "kWh",
			Signed:        false,
			RoundDecimals: 1,
		},
	},
)

var RegisterListBmv702 = mergeRegisters(
	RegisterListBmv700,
	Registers{
		"AuxVoltage": Register{
			Description:   "",
			Address:       0xED7D,
			Factor:        0.01,
			Unit:          "V",
			Signed:        false,
			RoundDecimals: 2,
		},
		/*
				"Synchronized": Register{
			Description: "",
					Address:       0xEEB6,
					Factor:        1,
					Unit:          "1",
					Signed:        false,
					RoundDecimals: 0,
				},
		*/
		"MidPointVoltage": Register{
			Description:   "",
			Address:       0x0382,
			Factor:        0.01,
			Unit:          "V",
			Signed:        false,
			RoundDecimals: 2,
		},
		"MidPointVoltageDeviation": Register{
			Description:   "",
			Address:       0x0383,
			Factor:        0.1,
			Unit:          "%",
			Signed:        true,
			RoundDecimals: 1,
		},
		/*
				"NumberOfLowAuxVoltageAlarms": Register{
			Description: "",
					Address:       0x030C,
					Factor:        1,
					Unit:          "",
					Signed:        false,
					RoundDecimals: 0,
				},
				"NumberOfHighAuxVoltageAlarms": Register{
			Description: "",
					Address:       0x030D,
					Factor:        1,
					Unit:          "",
					Signed:        false,
					RoundDecimals: 0,
				},
		*/
		"AuxVoltageMinimum": Register{
			Description:   "",
			Address:       0x030E,
			Factor:        0.01,
			Unit:          "V",
			Signed:        true,
			RoundDecimals: 2,
		},
		"AuxVoltageMaximum": Register{
			Description:   "",
			Address:       0x030F,
			Factor:        0.01,
			Unit:          "V",
			Signed:        true,
			RoundDecimals: 2,
		},
	},
)
