Version: 0                                                 # must be 0
ProjectTitle: Configurable Title of Project                # optional, default go-iotdevice: used as <title> in the http frontend
LogConfig: True                                            # optional, default False, outputs the configuration including defaults on startup
LogWorkerStart: True                                       # optional, default False, outputs what devices and mqtt clients are started
LogDebug: True                                             # optional, default False, outputs various debug information

Auth:                                                      # when this section is missing, login is not supported
  JwtSecret: Ra3aenaiqu7tie9Moozaedei6ahphiesh0dai5eexai2  # optional, default random, used to sign the JWT tokens
  jwtValidityPeriod: 2h                                    # optional, default 1h, users are logged out after this time
  HtaccessFile: ./auth.passwd                              # mandatory, where the file generated by htpasswd can be found

HttpServer:
  Bind: 0.0.0.0                                            # optional, default ::1 (ipv6 loopback)
  Port: 8000                                               # optional, default 8000
  LogRequests: True                                        # optional, default true, enables the http access log
  FrontendProxy: "http://127.0.0.1:3000/"                  # optional: default deactivated; otherwise an address of the frontend dev-server

Devices:
  0-solar:
    Kind: RandomSolar
  1-bmv:
    Kind: RandomBmv
  2-bmv:
    Kind: Vedirect
    Device: /dev/ttyUSB1
    LogDebug: True

Views:
  - Name: public
    Title: Simple
    Devices:
      0-solar:
        Title: Solar Charger
      1-bmv:
        Title: Battery One

  - Name: private
    Title: Details
    Devices:
      0-solar:
        Title: Solar Charger
      1-bmv:
        Title: Battery One
      2-bmv:
        Title: Battery Two
