Version: 1                                                 # must be 0
ProjectTitle: Piegn Development Project                    # optional, default go-iotdevice: used as <title> in the http frontend
LogConfig: True                                            # optional, default False, outputs the configuration including defaults on startup
LogWorkerStart: True                                       # optional, default False, outputs what devices and mqtt clients are started
LogStorageDebug: False                                     # optional, default False, outputs various debug information

Auth:                                                      # when this section is missing, login is not supported
  JwtSecret: Ra3aenaiqu7tie9Moozaedei6ahphiesh0dai5eexai2  # optional, default random, used to sign the JWT tokens
  JwtValidityPeriod: 2h                                    # optional, default 1h, users are logged out after this time
  HtaccessFile: ./auth.passwd                              # mandatory, where the file generated by htpasswd can be found

HttpServer:
  Bind: 0.0.0.0                                            # optional, default ::1 (ipv6 loopback)
  Port: 8001                                               # optional, default 8000
  LogRequests: True                                        # optional, default true, enables the http access log
  FrontendProxy: "http://127.0.0.1:3000/"                  # optional: default deactivated; otherwise an address of the frontend dev-server

MqttClients:
  1-piegn:
    Broker: tcp://mqtt.piegn.koestler.ch:1883
    #Broker: tcp://127.0.0.1:11883
    User: dev
    Password: zee4AhRi
    TelemetryInterval: 0s
    LogMessages: False
    LogDebug: False

MqttDevices:
  dev-v1-main-bmv:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-main-bmv/+
  dev-v1-main-solar:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-main-solar/+
  dev-v1-aux-bmv:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-aux-bmv/+
  dev-v1-aux-solar:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-aux-solar/+

VictronDevices:
  dev-random-bmv:
    Kind: RandomBmv
    General:
      LogDebug: False
      LogComDebug: False
      SkipFields:
        - Temperature
        - AuxVoltage
  dev-solar:
    Kind: Vedirect
    Device: /dev/tty.usbserial-VEHTVQT

  #dev-random-solar:
  #  Kind: RandomSolar
  #  General:
  #    LogDebug: False
  #    LogComDebug: False
  #    SkipFields:
  #      - BatteryTemperature

HttpDevices:
  dev-tcw241:
    Url: http://control0/
    #Url: http://192.168.8.108/
    Kind: Teracom
    Username: admin
    Password: zooBohz7
    PollInterval: 500ms
    General:
      LogDebug: True

  dev-shelly-em3:
    Url: http://shelly-em3-0/
    Kind: ShellyEm3
    Username: admin
    Password: jair6aiK
    PollInterval: 500ms
    General:
      LogDebug: True

Views:
  - Name: victron
    Title: Victron
    Autoplay: true
    Devices:
      - Name: dev-v1-main-bmv
        Title: v1 main bmv
      - Name: dev-v1-main-solar
        Title: v1 main solar
      - Name: dev-v1-aux-bmv
        Title: v1 aux bmv
      - Name: dev-v1-aux-solar
        Title: v1 aux solar

  - Name: local
    Title: Local Dev
    Autoplay: true
    AllowedUsers:
      - lk
    Devices:
      - Name: dev-tcw241
        Title: TCW 241
      - Name: dev-shelly-em3
        Title: Shelly EM3
        #- Name: dev-solar
        #  Title: local solar
        #- Name: dev-random-solar
        #  Title: random solar

