Version: 1                                                 # configuration file format; must be set to 1 for >v2 of this tool.
ProjectTitle: Configurable Title of Project                # optional, default go-iotdevice: is shown in the http frontend
LogConfig: True                                            # optional, default False, outputs the used configuration including defaults on startup
LogWorkerStart: True                                       # optional, default False, outputs what devices and mqtt clients are started
LogDebug: False                                            # optional, default False, outputs various debug information

HttpServer:                                                # optional, when missing: http server is not started
  Bind: "::1"                                              # optional, default ::1 (ipv6 loopback), what address to bind to, use "0:0:0:0" when started within docker
  Port: 8000                                               # optional, default 8000
  LogRequests: True                                        # optional, default true, enables the http access log to stdout
  # configure FrontendProxy xor FrontendPath
  #FrontendProxy: "http://127.0.0.1:3000/"                 # optional: default deactivated; proxies the frontend to another server; useful for development
  FrontendPath: ./frontend-build/                          # optional: default "frontend-build": path to a static frontend build
  FrontendExpires: 5m                                      # optional: default 5min, what cache-control header to send for static frontend files
  ConfigExpires: 1m                                        # optional: default 1min, what cache-control header to send for configuration endpoints
  LogDebug: False                                          # optional: default false, output debug messages related to the http server

Authentication:                                            # optional, when missing: login is disabled
  #JwtSecret: "insert a random string here and uncomment"  # optional, default random, used to sign the JWT tokens
  JwtValidityPeriod: 1h                                    # optional, default 1h, users are logged out after this time
  HtaccessFile: ./auth.passwd                              # mandatory, where the file generated by htpasswd can be found

MqttClients:                                               # optional, when empty, no mqtt connection is made
  local:                                                   # mandatory: an arbitrary name used for logging and for referencing in other config sections
    Broker: tcp://mqtt.example.com:1883                    # mandatory: the URL to the server, use tcp:// or ssl://
    ProtocolVersion: 5                                     # optional, default 5, must be 5 always, only mqtt protocol version 5 is supported
    User: dev                                              # optional, default empty, the user used for authentication
    Password: zee4AhRi                                     # optional, default empty, the password used for authentication
    #ClientId: go-iotdevice                                # optional, default go-iotdevice-UUID, mqtt client id, make sure it is unique per mqtt-server
    Qos: 1                                                 # optional, default 1, what quality-of-service level shall be used for published messages and subscriptions
    KeepAlive: 60s                                         # optional, default 60s, how often a ping is sent to keep the connection alive
    ConnectionRetryDelay: 10s                              # optional, default 10s, when disconnected: after what delay shall a connection attempt is made
    ConnectTimeout: 5s                                     # optional, default 5s, how long to wait for the SYN+ACK packet, increase on slow networks
    AvailabilityTopic: %Prefix%tele/%ClientId%/status      # optional, what topic to use for online/offline messages
    TelemetryInterval: 10s                                 # optional, default 10s, how often to sent telemetry mqtt messages, 0s disables tlemetry messages
    TelemetryTopic: %Prefix%tele/go-iotdevice/%DeviceName%/state # optional, what topic to use for telemetry messages
    TelemetryRetain: false                                 # optional, default false, the mqtt retain flag for telemetry messages
    RealtimeEnable: false                                  # optional, default false, whether to enable sending realtime messages
    RealtimeTopic: %Prefix%stat/go-iotdevice/%DeviceName%/%ValueName% # optional, what topic to use for realtime messages
    RealtimeRetain: true                                   # optional, default true, the mqtt retain flag for realtime messages
    TopicPrefix:                                           # optional, default empty, %Prefix% is replaced with this string
    LogMessages: False                                     # optional, default false, log all incoming mqtt messages
    LogDebug: False                                        # optional, default false, very verbose debug log of the mqtt connection

VictronDevices:                                            # optional, a list of Victron Energy devices to connect to
  solar0:                                                  # mandatory: an arbitrary name used for logging and for referencing in other config sections
    Kind: Vedirect                                         # mandatory: possibilities: Vedirect, RandomBmv, RandomSolar, always set to Vedirect expect for development
    General:                                               # optional, this section is exactly the same for all devices
      SkipFields:                                          # optional, default empty, a list of field names that shall be ignored for this device
        - Temperature                                      # for BMV devices without a temperature sensor connect
        - AuxVoltage                                       # for BMV devices without a mid- or starter-voltage reading
      SkipCategories:                                      # optional, default empty, a list of category names that shall be ignored for this device
        - Settings                                         # for solar devices it might make sense to not fetch / output the settings
      TelemetryViaMqttClients:                             # optional, default all clients, to what mqtt servers shall telemetry messages be sent to
        - local                                            # state the arbitrary name of the mqtt client as defined in the MqttClients section of this file
      RealtimeViaMqttClients:                              # optional, default all clients, to what mqtt servers shall realtime messages be sent to
        - local
      LogDebug: False                                      # optional, default false, enable debug log output
      LogComDebug: False                                   # optional, default false, enable a verbose log of the communication with the device
    Device: /dev/serial/by-id/usb-VictronEnergy_BV_VE_Direct_cable_VEHTVQT-if00-port0 # mandatory, the path to the usb-to-serial converter

MqttDevices:
  dev-v1-main-bmv:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-main-bmv/+
  dev-v1-main-solar:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-main-solar/+
  dev-v1-aux-bmv:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-aux-bmv/+
  dev-v1-aux-solar:
    MqttTopics:
      - piegn/stat/go-iotdevice/v1-aux-solar/+



  #dev-random-solar:
  #  Kind: RandomSolar
  #  General:
  #    LogDebug: False
  #    LogComDebug: False
  #    SkipFields:
  #      - BatteryTemperature

HttpDevices:
  dev-tcw241:
    Url: http://control0/
    #Url: http://192.168.8.108/
    Kind: Teracom
    Username: admin
    Password: zooBohz7
    PollInterval: 500ms
    General:
      LogDebug: True

  dev-shelly-em3:
    Url: http://shelly-em3-0/
    Kind: ShellyEm3
    Username: admin
    Password: jair6aiK
    PollInterval: 500ms
    General:
      LogDebug: True

Views:
  - Name: victron
    Title: Victron
    Autoplay: true
    Devices:
      - Name: dev-v1-main-bmv
        Title: v1 main bmv
      - Name: dev-v1-main-solar
        Title: v1 main solar
      - Name: dev-v1-aux-bmv
        Title: v1 aux bmv
      - Name: dev-v1-aux-solar
        Title: v1 aux solar

  - Name: local
    Title: Local Dev
    Autoplay: true
    AllowedUsers:
      - lk
    Devices:
      - Name: dev-tcw241
        Title: TCW 241
      - Name: dev-shelly-em3
        Title: Shelly EM3
        #- Name: dev-solar
        #  Title: local solar
        #- Name: dev-random-solar
        #  Title: random solar

